spring:
   main:
      web-application-type: none
   jmx:
      enabled: false
   application:
      name: Lego Commands
   datasource:
      client-config-dir: C:\Users\tvatt\.credentials\site5\database
      client-config-file: site5-database-configuration.json
      database-key-name: site5-dev-lego
      hikari:
         connection-timeout: 180000
         idle-timeout: 60000
         connection-test-query: SELECT 1
         initialization-fail-timeout: 60000
         auto-commit: false
         login-timeout: 60000
         minimum-idle: 40
         maximum-pool-size: 40
         validation-timeout: 60000
         pool-name: site5-mysql-jdbc-pool
         max-lifetime: 10000

lego:
   imaging:
      root-images-folder: C:/Users/tvatt/Desktop/lego-collection-photos
      root-inventory-items-folder: C:/Users/tvatt/Desktop/lego-collection-photos
      keywords-key-name: "Keywords:"

bitly:
   client-config-dir: C:\Users\tvatt\.credentials\bitly.api
   client-config-file: bitly-client-api-keys.json

logging:
   level:
      root: INFO
      org.apache.http: ERROR
      okhttp3: WARN

bricklink:
   rest:
      uri: https://api.bricklink.com/api/store/v1
      client-config-dir: C:\Users\tvatt\.credentials\bricklink
      client-config-file: bricklink-client-api-keys.json
   web:
      client-config-dir: C:\Users\tvatt\.credentials\bricklink
      client-config-file: bricklink-web.json
      pool:
         default-max-per-route: 20
         max-per-route: 20
         max-total: 50

flickr:
   client-config-dir: C:\Users\tvatt\.credentials\flickr.api
   client-config-file: flickr-client-api-keys.json
   application-name: lego-imaging
   debug-request: false
   debug-stream: false

shipstation:
   client-config-dir: C:\Users\tvatt\.credentials\shipstation.api
   client-config-file: shipstation-client-config.json

reference:
   static-reference:
      country: static/reference/iso-country-code-mapping.json

mybatis:
   type-aliases-package: com.vattima.lego.data.ibatis.type.aliases
   type-handlers-package: com.vattima.lego.data.ibatis.type.handler
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 1000
      default-statement-timeout: 30
      lazy-loading-enabled: true
   mapper-locations: com/vattima/lego/data/ibatis/*

debug: false
